### ISSUE TITLE
Latest Amazon changes to product API seemed to result in errors

### ISSUE THREAD

**Issue by ianlin0126** [phoet/asin#39]
I'm using the asin gem (https://github.com/phoet/asin) to make requests to Amazon Product API.

It has been working well for a whole year but a few days ago without making any changes I started noticing the same product API requests now return the following error:

```
<ItemLookupErrorResponse xmlns="http://ecs.amazonaws.com/doc/2011-08-01/"><Error><Code>SignatureDoesNotMatch</Code><Message>The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.</Message></Error><RequestId>314b6504-8845-43a1-bdf6-53b02bbc974b</RequestId></ItemLookupErrorResponse>'
RuntimeError: request failed with response-code='403'
    from /usr/local/rvm/gems/ruby-1.9.3-p484/gems/asin-2.0.1/lib/asin/client.rb:264:in `call'
    from /usr/local/rvm/gems/ruby-1.9.3-p484/gems/asin-2.0.1/lib/asin/client.rb:55:in `lookup'
    from (irb):5
    from /usr/local/rvm/gems/ruby-1.9.3-p484/gems/railties-3.2.8/lib/rails/commands/console.rb:47:in `start'
    from /usr/local/rvm/gems/ruby-1.9.3-p484/gems/railties-3.2.8/lib/rails/commands/console.rb:8:in `start'
    from /usr/local/rvm/gems/ruby-1.9.3-p484/gems/railties-3.2.8/lib/rails/commands.rb:41:in `<top (required)>'
    from script/rails:6:in `require'
    from script/rails:6:in `<main>'
```

The original request still works, so I'm assuming that some changes on Amazon product API made the asin gem incompatible:

```
http://webservices.amazon.com/onca/xml?AWSAccessKeyId=<my-key>&AssociateTag=<my-tag>&Keywords=apple&Operation=ItemSearch&ResponseGroup=ItemAttributes&SearchIndex=UnboxVideo&Service=AWSECommerceService&Timestamp=2014-07-25T23%3A57%3A23Z&Version=2011-08-01&Signature=<hash>
```

**Comment by kez** [comment]
If you're looking for a quick fix, you can "gem 'curb'" in your Gemfile and "skip over" trying to resolve the problem with HTTPI (I also had the above).

**Comment by phoet** [comment]
i can't find anything in HTTPI that would have any influence on this. my assumption is that some HTTP library changed the way it treats parameters (or whitespace) and thus there is a malformed signature.

if you can provide any further information post it here.

this is the [amazon troubleshooting guide](http://docs.aws.amazon.com/general/latest/gr/signature-v4-troubleshooting.html), just in case...
