### ISSUE TITLE
Too much debug info

### ISSUE THREAD

**Issue by monkeysuffrage** [phoet/asin#42]
How do I turn off the debug info?

**Comment by phoet** [comment]
By default asin is not logging anything. What Kind of debug info are you talking about? What is the configuration you are using?

If you expect to get reasonable help from opening an issue, I'd recommend that you try to give more context information. Being specific is important.

**Comment by monkeysuffrage** [comment]
I was getting tons of debug info. I was able to turn it off with:
`config.logger = nil`
I recommend making that the default because that's not fun to see.

**Comment by phoet** [comment]
@monkeysuffrage that's exactly what you need to do. i thought that this was actually the default, but it's not... https://github.com/phoet/asin/blob/master/lib/asin/configuration.rb#L37 

do you want to create a PR for it?

**Comment by monkeysuffrage** [comment]
Not if I'm the only one who has a problem with it, I guess it's ok. Thanks
for the gem, it works great.
