### ISSUE TITLE
Hashie::Rash namespace collision in newer versions of Hashie & Rash gems

### ISSUE THREAD

**Issue by corprew** [phoet/asin#45]
Hi.

In the current version of Hashie, Rash is used for a regular expression-based hash, and the Rash gem's definitions of Rash gets overridden by the Hashie Gem's own.  wzcolon has forked the gem to use a new namespace for the class.  (Hashie::Hash::Rash, see https://github.com/wzcolon/rash.)

Would you accept a pull request to point at the new version of Rash?  The tests currently pass but moving forward to the current version of Hashie is required for some other products.

**Comment by phoet** [comment]
Yes, please go ahead with the PR

Corprew Reed <notifications@github.com> schrieb am Mo., 8. Feb. 2016, 04:21:

**Comment by corprew** [comment]
https://github.com/phoet/asin/pull/46
