### ISSUE TITLE
How to get list of products for a particular store only

### ISSUE THREAD

**Issue by pmishra16** [phoet/asin#49]
I am using product advertising api for fetching amazon products. API returns product from different store.
I want to fetch products from my store only.

Let say "ABC" is my amazon store and I want to fetch all products belongs to "ABC" only.

Please help me.

**Comment by phoet** [comment]
@pmishra16 can you point me to the api documentation for what you are trying to achieve?

**Comment by pmishra16** [comment]
I have read gem documentation and http://docs.aws.amazon.com/AWSECommerceService/latest/DG/becomingDev.html to fetching product.

But now I want to fetch product from a my store only.

I am looking into this for a long time but didn't get any documentation anywhere.

**Comment by phoet** [comment]
sorry, i do not know either. once you have found out how to do that through the api and it's not supported in ASIN, feel free to re-open this ticket or create a new one.
